### ISSUE TITLE
Master CloudFormation Template Invalid for Database Stack

### ISSUE THREAD

**Issue by EndlessMe** [OHDSI/OHDSIonAWS#11] opened 2021-07-15 19:57 UTC
When I'm attempting to launch the Cloudformation Template to build the OHDSI stack, the Database layer is failing due to the template showing that the NumRedshiftNodes parameter is listed as Type "String". The master template conflicts and shows this of type Number.

**Comment by EndlessMe** [comment] 2021-07-15 21:00
Here's the error message I see when I'm attempting to build the stack in us-east-1

`Properties validation failed for resource RedshiftCluster with message: #/NumberOfNodes: expected type: Integer, found: String`

**Comment by omritoptix** [comment] 2021-07-18 12:37
+1

**Comment by EndlessMe** [comment] 2021-07-21 18:41
I've implemented a workaround for the time being wherein I created a new database stack CloudFormation template and pointed the master template to its location in S3. Redshift does not like receiving the empty parameter of `NumberOfNodes: ""` in the existing yaml file. Removing this line, and adjusting the template as follows will allow the database stack to build properly.
```
  NumRedshiftNodes:
    Default: 1
    Description: Specifies the  number of nodes in your Redshift cluster.
    Type: Number
```

```
Conditions:
  DeployMultiAZDB: 
    !Equals [ "Highly Available", !Ref DatabaseType ] 
  SingleNodeRedshift:
    !Equals [ 1, !Ref NumRedshiftNodes ]
  MultiNodeRedshift:
    !Not [ !Equals [ 1, !Ref NumRedshiftNodes ] ]
  Serverless:
    !Equals [ "Serverless", !Ref DatabaseType ]
  NotServerless:
    !Not [ !Equals [ "Serverless", !Ref DatabaseType ] ]

```

**Comment by JamesSWiggins** [comment] 2021-08-17 20:42
@EndlessMe @omritoptix Thank you for pointing this out.  This has been resolved in the latest version of the template as well as many other updates!

**Closed as completed by JamesSWiggins** 2021-08-17 20:42 UTC

**Comment by EndlessMe** [comment] 2021-08-18 16:29
@JamesSWiggins I'm not sure if there's something else that needs to be tweaked, but for whatever reason, the synthetic data tables didn't create successfully for me. I chose not to use the 23 million sets. The schemas were created, but there aren't any tables for any of these synthetic sets.

**Comment by JamesSWiggins** [comment] 2021-08-18 17:29
@EndlessMe Once the CloudFormation Stack is complete, the sample data sets are still being loaded in the background.  This can take some time (hours) depending on the number of data sets, size of the data sets, and the Redshift configuration you chose.  You can see if this is what's going on by looking at the deployment log (link in the CloudFormation Outputs).  Do you think this is what's happening?  If not, I'd be interested to see your cloud_init_output.log file.  It should be in the S3 bucket created by the CloudFormation stack.  Warning though that this file contains sensitive information, so don't share it publicly.

**Comment by EndlessMe** [comment] 2021-08-18 18:00
@JamesSWiggins Thanks for the reply! Yes, I've built this from your cloudformation template in the past and had no issues with the data automatically loading in Redshift. I've been watching the query tab and it's been at a complete halt at this point. Looking at the build log, it confirms that the OMOP tables never were built (I'm doing this in single node mode). There are a lot of errors being generated that look like the following:

`java.sql.SQLException: [Amazon](500310) Invalid operation: relation "synthea1k.person" does not exist;`

Where is the table generation script being kicked off? I've been trying to reverse engineer how you did this, but this part is a little bit of black magic at this point :) Maybe the schemas are being set but the tables are no longer being generated for single node version now that you split them in the database yaml?

**Comment by JamesSWiggins** [comment] 2021-08-18 18:19
@EndlessMe Hmm... I've tested it as single node as well, it really shouldn't make any difference from a schema creation or data loading perspective... I'm not sure, but it would be helpful to take a look at the cloud-init-output.log file.  It should be in an S3 bucket in your account with a name like '#ACCTID#-0483ab6e9ee9ffcf6-atlas'.  Could you e-mail it to me?  wiggjame@amazon.com

**Comment by EndlessMe** [comment] 2021-08-18 19:13
@JamesSWiggins That bucket only seems to contain the .war files for the Atlas web app. Do I instead have to go to the location where the cloudwatch logs were generated and attempt to download it after a set period of time?

**Comment by JamesSWiggins** [comment] 2021-08-18 19:25
@EndlessMe So, that means that the data loading script never finished for some reason.  The logs are uploaded to S3 at the end.  There are two ways to get the log.  Probably the easiest would be to connect to the temporary ec2 build instance (named 'ohdsi-temp-build-instance') and copy the log file off to S3 or similar.  It's located in /var/log/cloud-init-output.log.  Or, you can export the log data from CloudWatch Logs to S3 using this process:  https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3ExportTasksConsole.html.

If you don't mind doing it, I'd be curious to see what's going on.  Another thing that would be interesting is to know the parameters you used to deploy the Stack.  They are located on the Parameters tab in CloudFormation of your parent (first) OHDSIonAWS Stack.  Thanks for your help looking into this!

**Comment by EndlessMe** [comment] 2021-08-18 20:14
Sounds good! I'll export the logs as soon as I get the okay from the account owner.

In the meantime, Here are the params I'm using:




Key | Value | Resolved value
-- | -- | --
AccessCidr | 0.0.0.0/0 | -
Achillesv | 1.6.3 | -
Andromedav | 0.4.0 | -
AtlasSecurity | true | -
Atlasv | 2.9.1 | -
BigKNNv | 1.0.0 | -
CohortDiagnosticsv | 2.1.0 | -
CohortMethodv | 4.0.1 | -
Cyclopsv | 3.0.0 | -
DatabaseConnectorJarsv | 1.1.0 | -
DatabaseConnectorv | 4.0.0 | -
DatabaseInstanceType | db.t3.medium | -
DatabaseMasterPassword | **** | -
DatabaseType | Single Instance | -
DomainName | ohdsi | -
EBEndpoint |**** | -
EC2KeyName | **** | -
EmpiricalCalibrationv | 2.0.2 | -
Eunomiav | 1.0.1 | -
EvidenceSynthesisv | 0.2.3 | -
ExampleStudies | true | -
FeatureExtractionv | 3.1.1 | -
Hadesv | 1.0.0 | -
HostedZoneId | **** | -
HostedZoneName |**** | -
Hydrav | 0.1.1 | -
MethodEvaluationv | 2.0.0 | -
NumRedshiftNodes | 1 | -
OMOPv | 5.3.0 | -
OhdsiRToolsv | 1.9.1 | -
OhdsiSharingv | 0.2.2 | -
PatientLevelPredictionv | 4.0.5 | -
PredictionComparisonv | 1.0.0 | -
RStudioHomeDirectorySize | 50 | -
RStudioInstanceType | t3.large | -
RStudioUserList | **** | -
RedshiftInstanceType | dc2.large | -
SelfControlledCaseSeriesv | 2.0.0 | -
SelfControlledCohortv | 1.5.0 | -
Sources | CMSDESynPUF100k,CMSDESynPUF1k,synthea100k,synthea1k | -
SourcesBucket | ohdsi-sample-data | -
SqlRenderv | 1.6.8 | -
UseACMBoolean | true | -
UseRoute53Boolean | true | -
VPCcidr | 10.1.0.0/16 | -
WebAPIv | 2.9.1 | -
WebAsgMax | 2 | -
WebAsgMin | 2 | -
WebInstanceType | t3.medium | -
a1cidr | 10.1.2.0/24 | -
a2cidr | 10.1.3.0/24 | -
d1cidr | 10.1.4.0/24 | -
d2cidr | 10.1.5.0/24 | -
p1cidr | 10.1.0.0/24 | -
p2cidr | 10.1.1.0/24 | -

Additionally, I've enabled a site-to-site VPN between our internal trusted network and the OHDSI VPC

**Comment by JamesSWiggins** [comment] 2021-08-18 20:34
@EndlessMe You showed an entry from the log showing an error for Synthea 1k.  Did the others create successfully?  Or did they all fail?  I'm trying to replicate your setup using your parameters to see if I can get it to act the same way.

**Comment by EndlessMe** [comment] 2021-08-18 20:35
@JamesSWiggins All the OMOP tables failed. Some of the analysis tables were created, though.

**Comment by EndlessMe** [comment] 2021-08-18 20:41
I don't even see entries in the logs of the CREATE TABLE command occurring for any of those OMOP tables; I only see the schemas being created. Really strange.

**Comment by JamesSWiggins** [comment] 2021-08-20 15:39
Just for documentations sake, I worked with EndlessMe and we were not able to reproduce the issue.  Another deployment worked as expected.  Still not sure what caused this.
